# Welcome to Math 10! 

__TA__: Yasmeen Baki <ybaki@gmail.com>

__Discussion__: Tuesdays and Thursdays 10:00-10:50am in ALP 3600

__Office Hours__: Location and time TBD


***
# Jupyter Notebook Basics
- All work in Jupyter takes place in cells
- The two main types of cells we will use are Markdown cells and Code cells 
    - Markdown cells are used for text and explanations; this is an example of a Markdown cell
    - Code cells are where you will write your Python code


    
## <font color = blue> Question 1 (A) </font>
Create a new markdown cell by pressing on this cell and then clicking __Escape__. Press __b__ to create a new cell below, and then press __m__ to change it to a markdown cell. Press __Enter__ to edit the cell, and write a short self-introduction. Press __Command + Enter__ (__Ctrl + Enter__) to evaluate the cell.

Hi this Zhengran Ji. I am a thrid year math and data sceince major. I love doing sports and reading books. 

## Some Shorcuts
Jupyter has many keyboard shortcuts that will make your life easier. Here are a few of the most important:

- Press __Escape__ to switch to command mode and __Enter__ to switch to edit mode
- While in command mode, pressing __b__ inserts a cell below, while pressing __a__ inserts a cell above
- While in command mode, pressing __m__ or __y__ toggles between markdown and code cells, respectively
- Pressing __Command + Enter__ (__Ctrl + Enter__) runs a cell, while presseing __Option + Enter__ (__Alt + Enter__) runs a cell *and* inserts a new cell below
- Arrow keys can be used to switch between cells; pressing __d + d__ will delete a selected cell, and pressing __z__ will restore the deleted cell; __x__, __c__, and __v__ are used to cut, copy, and paste cells, respectively
- More shortcuts can be found [here](https://www.edureka.co/blog/wp-content/uploads/2018/10/Jupyter_Notebook_CheatSheet_Edureka.pdf)

## <font color = blue> Question 1 (B) </font>

Use only keyboard shortcuts to do the following. Create a new code cell, and evaluate 5 + 5 using __Option + Enter__ (__Alt + Enter__). Delete the new input cell that is created. Copy the cell that has your self-introduction and paste it below.



In [10]:
5+5

10

***
# Data Types in Python

## <font color = blue> Question 2 </font>
Complete the cell below so that each variable is assigned to the indicated data type. In a new cell, verify that each variable is the correct type by using __type()__.

In [11]:
#integer
a =  10

#float
b =1.1

#string
c = 'Zhengran Ji'

#list
d = [1,2,3,4]

#tuple
e = (1,2,3,4)

In [12]:
type(d)

list

In [13]:
type(e)

tuple

***
# Importing

Oftentimes we need to import libraries or modules that are not included with Python by default. Math 10 will make extensive use of the NumPy library, for example. Start by taking a look at some of the examples below. _Disclaimer: We will not work much with the math module in Math 10. The following examples are to help you learn the syntax for importing_.

In [1]:
# This command imports the entire math module
import math

In [2]:
# The math module contains many functions, but perhaps we need just a few of them
# Here we just import the sine and cosine functions.
from math import sin,cos

In [3]:
# It can be tedious to write math.function() every time we need it
# Here we give the math module our own name 
import math as m

In [4]:
m.sin(0)

0.0

In [45]:
m.cos(0)

1.0

<font color = red> *Warning*: You typically do not want to come up with your own name for modules and libraries. The above is meant to show syntax. All of the libraries we will use have widely accepted names. These names should be used to ensure readability of your code. </font>

## <font color = blue> Question 3 </font>
Import the numpy library as `np`. This is considered the conventional name, and using it makes it easier for others to read and understand your code.

In [5]:
import numpy as np

***
# Lists and List-like Data Structures

We previously saw an example of a list. What about a range? Evaluate the following cells.

In [6]:
range(3,10)

range(3, 10)

In [7]:
list(range(3,10)) #Notice that the right endpoint is not included here! This is common in Python.

[3, 4, 5, 6, 7, 8, 9]

In [8]:
type(range(3,10))

range

<font color = red> Food for thought: why does range exist as its own data type? Why not just use a list? </font>

## <font color = blue> Question 4 (A) </font>
Learn more about range by typing `help(range)`. You can also learn more about range by typing `range?` (The question mark is specific to Jupyter.) After reading the documentation, create a range object that starts at 5, does not go past 10, and has a step size of 2.

<font color = red> Tip: Don't worry if reading documentation feels confusing, this is normal. Try to at least read the first few lines. </font>

Let us now take a look at some NumPy specific structures. Notice that the following produces something very similar to range.

In [63]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(3,10,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

## <font color = blue> Question 4 (B) </font>
Try evaluating `range(3,10,0.5)`. Why do you get an error? Notice that we do not get an error if we try `np.arange(3,10,0.5)`.

In [15]:
range(3,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
np.arange(3,10,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

## <font color= blue> Question 4 (C) </font>
Using the help commands you learned above, get information about np.linspace(). Does it remind you of anything you have seen before (perhaps in Math 9)? When would it be better to use np.linspace() over np.arange()?

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

linspace is better when we wanna divide a gievn space into specific many pieces.

## <font color = blue> Question 4 (D)</font>
<a id='Q4'></a>
Again using the help commands, learn about `np.array()`. Define a variable `r` and set it equal to a range of your choice. Create the following variables so that `r` is converted the the corresponding data types. Check that each variable is the correct data type using `type()`.


In [21]:
r = range(1,10)

range

In [24]:
r_list = list(r)
r_tuple = tuple(r_list)
r_set = set(r_list)
r_array = np.array(r_list) 
print(type(r_list))
print(type(r_tuple))
print(type(r_set))
print(type(r_array))

<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'numpy.ndarray'>


The following code shows some exampls of operations that we can perform on lists and list-like objects.


In [25]:
r[0] #r[n] means to return the nth element of r. Warning: indexing starts at 0!

1

In [26]:
len(r) #Returns the length of r

9

In [27]:
5 in r #Checks whether or not 5 is an element of r

True

# Jupyter Magic Commands and Timing

There are a number of Jupyter-specific commands known as "magics". They are called using `%`, and a number of examples are given at [this link](https://www.edureka.co/blog/wp-content/uploads/2018/10/Jupyter_Notebook_CheatSheet_Edureka.pdf). Below we consider `%time` and `%timeit`. 

In [76]:
%time 5 in r_list

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.96 µs


True

In [81]:
%timeit 5 in r_list

90.7 ns ± 2.97 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In general, using `%timeit` is more accurate. `%time` runs a piece of code once, and the timing might be inaccurate due to background processes of your computer. `%timeit` repeats the code multiple times and typically
returns a more reliable result.

## <font color = blue> Question 5 (A) </font>

For each of the variables in [Question 4 (D)](#Q4), use `%timeit` and check whether or not 5 is contained in the data structure. Which structure takes the least amount of time to check?

_Bonus_: Try to create the largest range/list/tuple/set/array possible such that checking whether or not it contains 5 takes about 1 millisecond.

In [30]:
%timeit 5 in r_list
%timeit 5 in r_tuple
%timeit 5 in r_set
%timeit 5 in r_array

94.6 ns ± 7.34 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
82.4 ns ± 1.42 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
43.8 ns ± 0.604 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
1.96 µs ± 65.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## <font color = blue> Question 5 (B) </font>
Take a look at the cell below and answer the following question. Say you have a list and want to know if an element is in it. Why is converting the list to a set, and then checking in the set not the best idea?

In [82]:
%timeit set(r_list)

772 ns ± 3.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


It takes a lot more time than directly checking it in a list even though there might be duplicates. 