# UCI Math 10, Fall 2021

# Homework 1: Getting Started with Python

To get full credit on this (and every) homework, the notebook needs to be well-organized, containing all these cells it started with, and only what is needed for you to answer the questions.

You may submit this homework in a group of 1-3 total students.

**Suggestion**.  Make a copy of this notebook, do your work in the copy, and then put your final answers in the original.

**Due date**.  Due at 11:30am on Friday of Week 1, October 1st.

<p style="font-size:20px; color:blue; font-weight:bold">Question 0:</p>

Name(s): Zhengran Ji

UCI ID(s): 87537895

<p style="font-size:20px; color:blue; font-weight:bold">Question 1:</p>

Request a free [Streamlit cloud community account](https://forms.streamlit.io/cloud-sign-up).  You can put "Student" in the Job title section, and use your UCI email address.

<p style="color:red;">Write your name(s) here to indicate that you have requested an account (each individual student must request one account):Zhengran Ji

<p style="font-size:20px; color:blue; font-weight:bold">Question 2:</p>

Sign up for a free [GitHub account](https://github.com/). (UCI has their own GitHub, but we will not use the UCI GitHub, instead we will use the general public GitHub.)

<p style="color:red;">Put a link to your GitHub accounts (each individual student must have an account):
  
Make sure the link is clickable, like this [Chris Davis's GitHub page](https://github.com/ChristopherDavisUCI).  (If you want, you can use html to have the link display above in the red part, but it's probably easier to leave the red part, i.e., to go past the closing `</p>` tag, and then use Markdown syntax for a hyperlink, like this `[display text](url)`

[Zhengran Ji's page](https://github.com/jzr01)

<p style="font-size:20px; color:blue; font-weight:bold">Question 3:</p>

Say "Hi" in the "Hi" thread on Ed Discussion.  (If you already did that before seeing this homework, then you can just skip this question.)

<p style="font-size:20px; color:blue; font-weight:bold">Question 4:</p>
For each of the following data types in Python, list one possible advantage of that data type over a list.

* tuple
* set
* range
* numpy array

<p style="color:red;">Put your answers here:</p>

1. Tuple is a data structure that is not liable to change after created which you can use to store some data that you don't want to change. Also, it can be put into a set.
2. Set is a data structure that has no orders and no repeated elements, so if you want to create a data structure that store unique values, you can use set.
3. One of the advantage for range is that when range is create it does not occupioed the computer memory.
4. array is the only data structure can be reshaped through function, and it can has multi-dimensions.

<p style="font-size:20px; color:blue; font-weight:bold">Question 5:</p>

Describe in as much detail as you can, what the following error is referring to.

<p style="color:red;">Put your answer here:</p>

The element of a set cannot be a set, it must be immutable. 

In [1]:
a1 = "Chris"
a2 = {3,1,4,1}
a3 = (5,9,2)

for x in {a1,a2,a3}:
    print("Math 10")

TypeError: unhashable type: 'set'

<p style="font-size:20px; color:blue; font-weight:bold">Question 6:</p>
Write a function replace_elts(A) which takes as input a two-dimensional NumPy array A, and as output returns a NumPy array of the same shape, but where the entries less than 10 in A have been replaced by -2.

In [7]:
# Example
import numpy as np

In [6]:
rng = np.random.default_rng()
A = np.random.default_rng().integers(0,20,size=(4,10))
A

array([[14,  5,  9, 18,  0, 17,  7, 18, 13, 17],
       [ 1, 10,  6,  3, 10,  8,  5,  9,  6,  1],
       [ 7,  4,  7, 17,  3,  4,  8,  4, 14,  5],
       [17, 10,  6, 11, 11,  9,  8, 19, 15,  6]], dtype=int64)

In [8]:
def replace_elts(A):
    for i in range(len(A)):
        for j in range(len(A[i,:])):
            if A[i,j] < 10:
                A[i,j] = -2
    return A

In [9]:
replace_elts(A)

array([[14, -2, -2, 18, -2, 17, -2, 18, 13, 17],
       [-2, 10, -2, -2, 10, -2, -2, -2, -2, -2],
       [-2, -2, -2, 17, -2, -2, -2, -2, 14, -2],
       [17, 10, -2, 11, 11, -2, -2, 19, 15, -2]], dtype=int64)

<p style="font-size:20px; color:blue; font-weight:bold">Question 7:</p>

Write a function `make_array(m,n)` that takes as input two positive integers m and n, and as output returns an $m \times n$ NumPy array which is 0, 1, ..., n-1 in the top row, which is 1, 2, ..., n in the next row, and which is m-1, ..., m+n-2 in the bottom row.

More details: 
* Then Use `np.zeros` to create an initial array of all zeros.  
* Look at the documentation for np.zeros and provide an argument so that the array holds 8-bit integers.  (It may be easier to use Google to figure out how to specify 8-bit integers in NumPy.  Don't be intimidated if you find writing you don't understand... skim through that writing and try to figure out how to make 8-bit integers.  Don't use unsigned integers.)
* For actually filling numbers into the array, use for loops (maybe nested for loops, or maybe one for loop and one range).

In [2]:
# Example
import numpy as np

In [10]:
def make_array(row,column):
    A = np.zeros((row,column))
    for i in range(row):
        A[i,0] = i
        for j in range(1,column):
            A[i,j]  = A[i,0]+j
    return A

In [11]:
make_array(3,5)

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

<p style="font-size:20px; color:blue; font-weight:bold">Question 8:</p>

Explain the error message from the next cell.

<p style="color:red;">Put your answer here:</p>

1. In this case, Python consider the input z as one tuple. Since our function is defined with 2 inputs, we are missing anothe one.

In [12]:
z = (3,5)
make_array(z)

TypeError: make_array() missing 1 required positional argument: 'column'

<p style="font-size:20px; color:blue; font-weight:bold">Question 9:</p>

Why does the output of following cell seem to be wrong?

<p style="color:red;">Put your answer here:</p>

1. Since the format of the number is int8, it only gives up 256 numbers which is from -128 to 127. So when the number exceed 127, it will shows as negative number.

In [21]:
A = make_array(126,10)
A[-3:] # We're asking for the last three rows of the array A.

array([[ 123,  124,  125,  126,  127, -128, -127, -126, -125, -124],
       [ 124,  125,  126,  127, -128, -127, -126, -125, -124, -123],
       [ 125,  126,  127, -128, -127, -126, -125, -124, -123, -122]],
      dtype=int8)