<h1 style="color:red">Remember to start recording!</h1>

# Week 1 Friday Lecture

Download the csv file "indexData.csv" from Files->Datasets on Canvas.  Save the file somewhere you can access on the computer.
This "indexData.csv" comes from [here](https://www.kaggle.com/mattiuzc/stock-exchange-data), but I changed the name of the first column so you should use the version on Canvas, not the version on Kaggle.

Goals for today:
* Introduce dictionaries, an important data type.
* Introduce the library pandas (for working with spreadsheet-like data)
* Similarity: both of these involve "named" data entries.

## Aside: listing folder contents in Python

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\zheng\\OneDrive\\Desktop'

In [4]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'Anaconda Navigator (Anaconda3).lnk',
 'CompSci 178',
 'Course Plan.xlsx',
 'CV',
 'desktop.ini',
 'Discord.lnk',
 'Eclipse IDE for Java Developers - 2021-09.lnk',
 'Econ 105A',
 'Excel.lnk',
 'GitHub Desktop.lnk',
 'Honor Program',
 'ICS 139W',
 'ICS 33',
 'indexData.csv',
 'Jupyter Notebook (Anaconda3).lnk',
 'Math 10',
 'Math 120A',
 'Math 130A Grader',
 'MATLAB R2020b.lnk',
 'Order Confirmation.pdf',
 'PowerPoint.lnk',
 'rstudio.lnk',
 'Schedule',
 'Slack.lnk',
 'Summer 2022 Intership Info.docx',
 'Visual Studio Code.lnk',
 'Week 1 - Friday Lecture.ipynb',
 'Word.lnk',
 'Zoom.lnk']

In [6]:
# On a Windows computer, instead try !dir
!dir

 Volume in drive C is Windows-SSD
 Volume Serial Number is 9AFD-0117

 Directory of C:\Users\zheng\OneDrive\Desktop

10/01/2021  12:01 PM    <DIR>          .
10/01/2021  12:01 PM    <DIR>          ..
10/01/2021  12:01 PM    <DIR>          .ipynb_checkpoints
09/23/2021  12:03 PM               993 Anaconda Navigator (Anaconda3).lnk
09/27/2021  06:06 PM    <DIR>          CompSci 178
09/01/2021  11:10 PM            10,598 Course Plan.xlsx
08/17/2021  06:31 PM    <DIR>          CV
09/22/2021  06:23 PM             2,244 Discord.lnk
09/18/2021  10:31 AM             1,107 Eclipse IDE for Java Developers - 2021-09.lnk
09/28/2021  03:17 PM    <DIR>          Econ 105A
07/20/2021  07:22 PM             2,414 Excel.lnk
07/20/2021  07:22 PM             2,384 GitHub Desktop.lnk
09/21/2021  04:03 PM    <DIR>          Honor Program
09/27/2021  06:07 PM    <DIR>          ICS 139W
09/23/2021  05:00 PM    <DIR>          ICS 33
10/01/2021  11:44 AM         8,681,210 indexData.csv
09/23/2021  09:57 AM       

In [8]:
# This means: list all the files (and folders) up one level, in the data folder.
# Might need a backslash instead of a front slash on a different computer.
# This only works if there is a folder called data there.
os.listdir("..")

['.849C9593-D756-4E56-8D6E-42412F2A707B',
 'Desktop',
 'desktop.ini',
 'Documents',
 'Getting started with OneDrive.pdf',
 'N2 N K.dm3_tags.txt',
 'Personal Vault.lnk',
 'Pictures']

In [9]:
# More robust, but still only works if there is a data folder up one level.
os.listdir(os.path.join("..","data"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: '..\\data'

## Dictionaries

In [15]:
roles = {"chris": "teacher", "yasmeen": "TA", 
         "xingshuo": "LA", "chupeng": "LA"}

In [16]:
roles['chris']

'teacher'

## pandas

In [17]:
import pandas as pd
import numpy as np

In [22]:
A = np.arange(40).reshape([10,4])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [23]:
A.shape

(10, 4)

In [25]:
A = np.arange(40).reshape([-1,5]) #-1 means that sutomatic calculate

In [26]:
list(A)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34]),
 array([35, 36, 37, 38, 39])]

In [27]:
df = pd.DataFrame(A)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39

In [28]:
type(df)

pandas.core.frame.DataFrame

In [31]:
df = pd.DataFrame(A,columns = ['a','b','c','d','e'])
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39

In [37]:
df = pd.DataFrame(A,columns = list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39

In [46]:
df.index = list('abcdefgh')
df

a   b   c   d   e
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29
g  30  31  32  33  34
h  35  36  37  38  39

In [49]:
#panda series
s = df['a']
type(s)


pandas.core.series.Series

In [50]:
# Your path will be different!
df = pd.read_csv('C:\\Users\\zheng\\OneDrive\\Desktop\\indexData.csv')
df

Name      Date         Open         High          Low        Close  \
0        NYA  12/31/65   528.690002   528.690002   528.690002   528.690002   
1        NYA    1/3/66   527.210022   527.210022   527.210022   527.210022   
2        NYA    1/4/66   527.840027   527.840027   527.840027   527.840027   
3        NYA    1/5/66   531.119995   531.119995   531.119995   531.119995   
4        NYA    1/6/66   532.070007   532.070007   532.070007   532.070007   
...      ...       ...          ...          ...          ...          ...   
112452  N100   5/27/21  1241.119995  1251.910034  1241.119995  1247.069946   
112453  N100   5/28/21  1249.469971  1259.209961  1249.030029  1256.599976   
112454  N100   5/31/21  1256.079956  1258.880005  1248.140015  1248.930054   
112455  N100    6/1/21  1254.609985  1265.660034  1254.609985  1258.579956   
112456  N100    6/2/21  1258.489990  1263.709961  1258.239990  1263.619995   

          Adj Close       Volume  
0        528.690002          0.0  
1        527.210022          0.0  
2        527.840027          0.0  
3        531.119995          0.0  
4        532.070007          0.0  
...             ...          ...  
112452  1247.069946  379696400.0  
112453  1256.599976  160773400.0  
112454  1248.930054   91173700.0  
112455  1258.579956  155179900.0  
112456  1263.619995  148465000.0  

[112457 rows x 8 columns]

In [57]:
# let's find how many days was the high - low for NY bgger than 5% of the open value
df_NYA = df[df['Name'] == 'NYA']
df_NYA

Name      Date          Open          High           Low         Close  \
0      NYA  12/31/65    528.690002    528.690002    528.690002    528.690002   
1      NYA    1/3/66    527.210022    527.210022    527.210022    527.210022   
2      NYA    1/4/66    527.840027    527.840027    527.840027    527.840027   
3      NYA    1/5/66    531.119995    531.119995    531.119995    531.119995   
4      NYA    1/6/66    532.070007    532.070007    532.070007    532.070007   
...    ...       ...           ...           ...           ...           ...   
13943  NYA   5/24/21  16375.000000  16508.519530  16375.000000  16464.689450   
13944  NYA   5/25/21  16464.689450  16525.810550  16375.150390  16390.189450   
13945  NYA   5/26/21  16390.189450  16466.339840  16388.320310  16451.960940   
13946  NYA   5/27/21  16451.960940  16546.359380  16451.960940  16531.949220   
13947  NYA   5/28/21  16531.949220  16588.689450  16531.949220  16555.660160   

          Adj Close        Volume  
0        528.690002  0.000000e+00  
1        527.210022  0.000000e+00  
2        527.840027  0.000000e+00  
3        531.119995  0.000000e+00  
4        532.070007  0.000000e+00  
...             ...           ...  
13943  16464.689450  2.947400e+09  
13944  16390.189450  3.420870e+09  
13945  16451.960940  3.674490e+09  
13946  16531.949220  5.201110e+09  
13947  16555.660160  4.199270e+09  

[13948 rows x 8 columns]

In [58]:
df_NYA.shape

(13948, 8)

In [61]:
df_NYA[(df_NYA['High']-df_NYA['Low'])/df_NYA['Open']  > 0.05]

Name     Date         Open          High          Low         Close  \
10586  NYA  1/23/08  8661.059570   8806.099609  8343.620117   8805.679688   
10749  NYA  9/15/08  8091.569824   8091.569824  7680.149902   7680.149902   
10752  NYA  9/18/08  7440.390137   7806.410156  7318.839844   7775.160156   
10753  NYA  9/19/08  7775.169922   8201.240234  7775.169922   8187.129883   
10759  NYA  9/29/08  7890.370117   7890.370117  7167.770020   7204.009766   
...    ...      ...          ...           ...          ...           ...   
13644  NYA  3/17/20  9726.179688  10154.160160  9484.650391  10063.360350   
13645  NYA  3/18/20  9562.490234   9666.570313  8953.599609   9384.599609   
13646  NYA  3/19/20  9313.759766   9622.209961  9048.360352   9461.309570   
13647  NYA  3/20/20  9577.900391   9676.940430  9108.150391   9133.160156   
13650  NYA  3/25/20  9749.799805  10303.900390  9591.740234   9961.379883   

          Adj Close        Volume  
10586   8805.679688  3.241600e+08  
10749   7680.149902  8.279510e+09  
10752   7775.160156  1.008269e+10  
10753   8187.129883  9.387170e+09  
10759   7204.009766  7.305060e+09  
...             ...           ...  
13644  10063.360350  8.358500e+09  
13645   9384.599609  8.755780e+09  
13646   9461.309570  7.946710e+09  
13647   9133.160156  9.044690e+09  
13650   9961.379883  8.285670e+09  

[66 rows x 8 columns]