# UCI Math 10, Fall 2021

# Week 2, Monday In-class Worksheet

You may submit this worksheet in a group of 1-3 total students.

These worksheets are graded for effort, not for correctness.

**Due date**.  Due at 5:00pm on Tuesday of Week 1.

<p style="font-size:20px; color:blue; font-weight:bold">Question 0:</p>

Name(s): Zhengran Ji

UCI ID(s): 87537895

## Motivating question:

* If we roll five distinct six-sided dice, what is the probability that the number of 1s rolled is equal to the number of 2s rolled?

This combinatorics question can be solved directly without a computer (if you're interested, try to to figure out where these numbers come from, or try to come up with an alternative method for getting this same answer):
$$
\text{prob} = \left(\frac{4}{6}\right)^5 + 20 \, \left(\frac{1}{6}\right)^2 \left(\frac{4}{6}\right)^3 + 30 \,\left(\frac{1}{6}\right)^4 \left(\frac{4}{6}\right) = \frac{101}{324} \approx 0.311728395
$$
In this notebook, we'll solve the question in several different ways in Python.
* [A probability estimate using NumPy](#A-probability-estimate-using-NumPy)
* [A probability estimate using pandas](#A-probability-estimate-using-pandas)
* (Optional) [The exact probability using itertools.product](#The-exact-probability-using-itertools.product)

In [2]:
import numpy as np
import pandas as pd
from itertools import product

## A probability estimate using NumPy
Strategy:
* Set a value of $n$ for "number of experiments"
* Make an $n \times 5$ NumPy array of random integers, where each row represents rolling five distinct 6-sided dice.  (Be sure to construct this array without any loops.  Use a random number generator in Python, constructed using `np.random.default_rng()`.)
* Count how many of the experiments were successful.
* Estimate the probability using the formula "number of successes" divided by "number of experiments".
* If your answer does not equal the exact probability to at least three decimal places, try increasing $n$ (or looking for mistakes!).

Here is an example of counting 6s in a NumPy array.

In [9]:
A = np.array([[1, 4, 2, 6, 6],
       [5, 6, 4, 3, 5],
       [4, 4, 3, 4, 3],
       [1, 5, 5, 3, 3],
       [3, 1, 6, 2, 5]])

In [10]:
# B has the same shape as A
# B contains True where A contains 6.
B = (A == 6)
B

array([[False, False, False,  True,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False]])

In [11]:
B.dtype

dtype('bool')

In [15]:
# To count Trues, you can add them.
True + True + False

2

In [20]:
# axis = 0 means: add along the columns, one column at a time.
# axis = 1 means: add along the rows, one row at a time
# (Make sure you understand these examples.)
B.sum(axis = 0)

array([0, 1, 1, 1, 1])

In [21]:
B.sum(axis = 1)

array([2, 1, 0, 0, 1])

<p style="font-size:20px; color:blue; font-weight:bold">Question 1:</p>

Put your code for the NumPy estimate here.  The answer should be correct to three decimal places.

In [11]:
n = 10**3
#rng = np.random.default_rng()
A = np.random.randint(1,7,size = (n,5))
A1 = A == 1
A1 = A1.sum(axis = 1)

A2 = A == 2
A2 = A2.sum(axis = 1)

n = sum(A1 == A2)
n/

## A probability estimate using pandas

We make a similar computation here to practice with pandas.

In [2]:
A = np.array([[1, 4, 2, 6, 6],
       [5, 6, 4, 3, 5],
       [4, 4, 3, 4, 3],
       [1, 5, 5, 3, 3],
       [3, 1, 6, 2, 5]])

In [3]:
# Convert the NumPy array to a pandas DataFrame
df = pd.DataFrame(A)
df

0  1  2  3  4
0  1  4  2  6  6
1  5  6  4  3  5
2  4  4  3  4  3
3  1  5  5  3  3
4  3  1  6  2  5

In [5]:
df2 = (df == 6)
df2

0      1      2      3      4
0  False  False  False   True   True
1  False   True  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False   True  False  False

In [6]:
# Note how similar this code is to the NumPy code.
df2.sum(axis = 0)

0    0
1    1
2    1
3    1
4    1
dtype: int64

In [7]:
df2.sum(axis = 1)

0    2
1    1
2    0
3    0
4    1
dtype: int64

In [8]:
# Example of making a new column
df["sixes"] = df2.sum(axis = 1)
df

0  1  2  3  4  sixes
0  1  4  2  6  6      2
1  5  6  4  3  5      1
2  4  4  3  4  3      0
3  1  5  5  3  3      0
4  3  1  6  2  5      1

<p style="font-size:20px; color:blue; font-weight:bold">Question 2:</p>

Put your code for the pandas estimate here.  Try to use a big enough dataframe (and efficient enough code) that the answer is correct to three decimal places.

In [ ]:
n = 10**7
A = np.random.randint(1,7,size = (n,5))
df = pd.DataFrame(A)
df1 = (df == 1)
df['amount1'] = df1.sum(axis = 1)
df2 = (df == 2)
df['amount2'] = df2.sum(axis = 1)
df
df3 = df['amount1'] == df['amount2']
P = sum(df3==True)/n
print(format(P,'.3f'))

## The exact probability using itertools.product

<p style="color:red; font-weight:bold">(Optional)</p>

This is good practice but we may not cover itertools in Math 10, so you can skip this if you prefer.

In [51]:
product(["a","b","c"],[0,1,10])

In [52]:
list(product(["a","b","c"],[0,1,10]))

[('a', 0),
 ('a', 1),
 ('a', 10),
 ('b', 0),
 ('b', 1),
 ('b', 10),
 ('c', 0),
 ('c', 1),
 ('c', 10)]

In [40]:
list(product(range(2),repeat=4))

[(0, 0, 0, 0),
 (0, 0, 0, 1),
 (0, 0, 1, 0),
 (0, 0, 1, 1),
 (0, 1, 0, 0),
 (0, 1, 0, 1),
 (0, 1, 1, 0),
 (0, 1, 1, 1),
 (1, 0, 0, 0),
 (1, 0, 0, 1),
 (1, 0, 1, 0),
 (1, 0, 1, 1),
 (1, 1, 0, 0),
 (1, 1, 0, 1),
 (1, 1, 1, 0),
 (1, 1, 1, 1)]

In [41]:
# We can't use this kind of syntax to count 1s,
# even though it works in both NumPy and pandas:
my_tuple = (1,0,1,1)
my_tuple == 1

False

In [43]:
# Here is a method to count:
my_tuple.count(1)

3

<p style="font-size:20px; color:blue; font-weight:bold">Question 3:</p>

Compute the exact probability using product from the itertools module.  (You might think this way is better than the NumPy and pandas methods, but the NumPy and pandas methods generalize better to bigger problems, where we cannot explicitly list every combination.)

In [18]:
A = list(product(range(1,7),repeat=5))
my_list1 = []
my_list2 = []
for i in range(len(A)):
    my_list1.append(A[i].count(1))
    my_list2.append(A[i].count(2))

m = 0
for i in range(len(my_list1)):
    if my_list1[i] == my_list2[i]:
        m += 1

P = m /len(A)
print(format(P,'.3f'))

0.312
